knotitproject/knotitapp/urls.py
from .views import *
from django.urls import path, include

app_name = "knotitapp"

urlpatterns = [
    path('', home, name='home'),
    path('register/', register_user, name="register"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
    path('knots/', knots_list, name='knots'),
    path('knots/form', knot_form, name='knot_form'),
    path('knots/<int:knot_id>/', knot_details, name='knot'),
    path('knots/<int:knot_id>/form/', knot_edit_form, name='knot_edit_form'),
    path('times/', times_list, name='times'),
    path('times/<int:time_id>/', time_details, name='time'),
    path('times/form', time_form, name='time_form'),
    path('times/<int:time_id>/form/', time_edit_form, name='time_edit_form'),
]

knotitproject/knotitproject/urls.py
from django.contrib import admin
from django.urls import path, include
from knotitapp.models import *
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('knotitapp.urls'))
]
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knotitproject/knotitapp/models/knot.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import IntegrityError
from django.urls import reverse

class Knot(models.Model):
    name = models.CharField(max_length=50, default='')
    rope_type = models.CharField(max_length=50, default='')
    image = models.ImageField(upload_to='images/', null=True)
    how_to_video = models.FileField(upload_to='videos/', null=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

class Meta:
        verbose_name =("knot")
        verbose_name_plural = ("knots")

def __str__(self):
    return self.name

def get_absolute_url(self):
    return reverse("_detail", kwargs={"pk": self.pk})

knotitproject/knotitapp/models/time.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .knot import Knot

class Time(models.Model):

    time = models.CharField(max_length=50)
    knot = models.ForeignKey(Knot, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)

    class Meta:
            verbose_name =("time")
            verbose_name_plural = ("times")

    def __str__(self):
        return u'{0}'.format(self.name)

    def get_absolute_url(self):
        return reverse("_detail", kwargs={"pk": self.pk})

knotitproject/knotitapp/templates/home/home.html
{% extends 'shared/base.html' %}
{% load static%}


{% block css %}
    <link rel="stylesheet" href="{% static 'styles/home.css' %}"/>
{% endblock %}

{% block content %}

    <h1 style="text-align: center">Welcome to Knot It!</h1>
    <h2 style="text-align: center"><a href="{% url 'knotitapp:knot_form' %}">Create A Knot From The List</a></h2>
      <div class="list-type3">
        <ul>
            <li class="card"><b>Over Hand Knot</b>: Safety knot </li>
            
            <li class="card"><b>Square Knot</b>: Joins the end of two ropes under tension</li>
            
            <li class="card"><b>Girth Hitch</b>: Attaches webbing or cord to an anchor or harness</li>
            
            <li class="card"><b>Figure Eight Bend</b>: To join the ends of two ropes</li>
            
            <li class="card"><b>Water Knot</b>: Joins the ends of tubular webbing</li>
            
            <li class="card"><b>Bowline</b>: To anchor a rope</li>
            
            <li class="card"><b>Triple Bowline</b>: To anchor a bite of rope(not the end of the rope)</li>
            
            <li class="card"><b>Clove Hitch</b>: Anchors the end of rope under tension</li>
            
            <li class="card"><b>Clove Hitch Middle of Rope</b>: Forms and anchor in the middle of rope</li>
            
            <li class="card"><b>Double Figure Eight</b>: Forms a fixed loop in rope</li>
            
            <li class="card"><b>Figure Eight Slip Knot</b>: Creates an adjustable bite in rope</li>
            
            <li class="card"><b>Middle of the Rope Prusik</b>: Moveable friction hitch</li>
            
            <li class="card"><b>End of the Rope Prusik</b>: Moveable friction hitch at the end of a rope</li>
            
            <li class="card"><b>Rerouted Figure of Eight</b>: To tie into a climbing rope</li>
            
            <li class="card"><b>Munter Hitch</b>: Forms a mechanical belay</li>
            
            <li class="card"><b>Super Munter Hitch</b>: Creates a high friction lower</li>
            
            <li class="card"><b>Auto Block</b>: Moveable friction hitch with rope or webbing, releaseable</li>
            
            <li class="card"><b>Munter Mule Knot</b>: Creates a releasable anchor knot</li>
        </ul>
      </div>
{% endblock %}

knotitproject/knotitapp/templates/knots/details.html
  
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/knotdetails.css' %}" />
{% endblock %}

   {% block title %}
            Knots
   {% endblock %}
    

{% block content %}
    <h1 style="text-align: center">Your Knot</h1>
    <div class="card">
     <section style="text-align: center">
      <form action="{% url 'knotitapp:knot_edit_form' knot.id %}" method="GET">
        {% csrf_token %}
        <button>Edit</button>
      </form>
      
       <form action="{% url 'knotitapp:knot' knot.id %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE">
        <button>Delete</button>
      </form>

    </section>
            <p style="text-align: center"><b>Name:</b> {{knot.name}}</p>
            <p style="text-align: center"><b>Rope Type:</b>  {{knot.rope_type}}</p>
            <p style="text-align: center"><video controls src="{{MEDIA_URL}}{{knot.how_to_video}}" type="video/mp4" alt="how_to_video" height="300" width="200">
            </video></p>
            <p style="text-align: center"><img src="{{MEDIA_URL}}{{knot.image}}" alt="image" height="200" width="150"></p>
{% endblock %}

knotitproject/knotitapp/templates/knots/form.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/knotform.css' %}"/>
{% endblock %}

{% block content %}

    {% if knot_id is not None %}
        <h1 style="text-align: center" style="color: white">Edit Knot</h1>
        <form action="{% url 'knotitapp:knot_edit_form' knot_id %}" method="post" enctype="multipart/form-data">
    {% else %}
        <h1 style="text-align: center">New Knot</h1>
        <form action="{% url 'knotitapp:knot_form' %}" method="post" enctype="multipart/form-data">
    {% endif %}
    {% csrf_token %}
    <div style="text-align: center" class="card">{{ form.as_p }}</div>
        {% if knot_id is not None %}
            <input  type="hidden" name="actual_method" value="PUT">
            <div style="text-align: center"><input type="submit" value="Update" /></div>
        {% else %}
            <div style="text-align: center"><input  type="submit" value="Create" /></div>
        {% endif %}
      </form>
    
{% endblock %}

knotitproject/knotitapp/templates/knots/list.html
{% extends 'shared/base.html' %}
{% load static%}
 {% block css %}
     <link rel="stylesheet" href="{% static 'styles/knotlist.css' %}" /> 
{% endblock %}

   {% block title %}
            Knots
   {% endblock %}
    

{% block content %}


    <h1 style="text-align: center">Knots</h1>

    <div style="text-align: center"><a  href="{% url 'knotitapp:knot_form' %}">Add Knot</a></div>

    <div>
    <ol>
    {% for knot in all_knots %}
        <li style="text-align: center" class="card">
            <p><b>Knot:</b><a href="{% url 'knotitapp:knot' knot.id %}">{{knot.name}}</a></p>
            <p><b>Rope:</b> {{knot.rope_type}}</p>
        </li>
    {% endfor %}
    </ol>
    </div>
{% endblock %}

knotitproject/knotitapp/templates/shared/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
           Knot It!
    </title>
    <link rel="stylesheet" href="{% static 'styles/base.css' %}"/>

    {% block css %}
    {% endblock %}
</head>

<body>
    <nav>
        <ul class="navList">
            <li><b>Knot It!</b></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'knotitapp:home' %}">Home</a></li><br/>
                <li><a href="{% url 'knotitapp:knots' %}">Knots</a></li>
                <li><a href="{% url 'knotitapp:times' %}">Times</a></li>
                <li><a href="{% url 'knotitapp:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'knotitapp:login' %}">Login</a></li>
                <li><a href="{% url 'knotitapp:register' %}">Register</a></li>
            {% endif %}
        </ul>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock scripts %}

</body>

</html>

knotitproject/knotitapp/templates/times/form.html
{% extends 'shared/base.html' %}
{% load static%}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/timeform.css' %}"/>
{% endblock %}

{% block content %}

    {% if time.id is not None %}
    <h1 style="text-align: center">Edit Time</h1>
    <form action="{% url 'knotitapp:time' time.id %}" method="post">
    {% else %}
        <h1 style="text-align: center">New Time</h1>
        <form action="{% url 'knotitapp:times' %}" method="post">
        {% endif %}
        {% csrf_token %}
        <div class="card">
          <div style="text-align: center">
            <label style="text-align: center" for="time">Time: </label>
            <input style="text-align: center" required id="time" type="text" name="time" placeholder="00(MM):00(SS)" value="{{time.time}}" required><br/>
          </div>
          <div style="text-align: center">
            <label style="text-align: center" for="knot">Knot: </label>
            <select class="select" style="text-align: center" required id="knot_id" type="text" name="knot" value"{{knot.knot_id}}" required>
            <option value="" selected="selected" disabled>Select Knot</option>
                    {% for knot in all_knots %}
                        <option value="{{ knot.id }}">{{ knot.name }}</option>
                    {% endfor %} 
            </select><br/>
          </div>
          <div style="text-align: center">
        {% if time.id is not None %}
            <input style="text-align: center" type="hidden" name="actual_method" value="PUT">
            <input style="text-align: center" type="submit" value="Update" />
        {% else %}
            <input style="text-align: center" type="submit" value="Create" />
        {% endif %}
        </div>
      </div>  
    </form>
{% endblock %}

knotitproject/knotitapp/templates/times/list.html
{% extends 'shared/base.html' %}
{% load static%}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/timelist.css' %}" />
{% endblock %}

   {% block title %}
            Times
   {% endblock %}
    

{% block content %}


    <h1 style="text-align: center">Times</h1>

    <fieldset style="margin-inline-start: 400px; margin-inline-end: 400px;">
        <div style="text-align: center"><label class="items" for="knot" style="color: white">Sort Times By Knot</label></div>
        <div style="text-align: center"><select id="knot" type="text" name="knot"></div>
        <option value="" selected="selected" disabled>Select Knot</option>
            {% for knot in all_knots %}
                <option {% if knot.id == knot_id %}selected{% endif %} value="{{knot.id}}">{{ knot.name }}</option>
            {% endfor %}
        </select>
    </fieldset></br>

    <div style="text-align: center"><a href="{% url 'knotitapp:time_form' %}">Add Time</a></div>
    <ol>
    {% for time in all_times %}
        <li style="text-align: center" class="card">
            <p><b>Time:</b> {{time.time}}</a></p>
            <p><b>Knot:</b> {{time.knot__name}}</p>

        <form action="{% url 'knotitapp:time_edit_form' time.id %}" method="GET">
              {% csrf_token %}
              <button>Edit</button>
        </form>
        
        <form action="{% url 'knotitapp:time' time.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/knots.js' %}"></script>
{% endblock %}